config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "lists#index"
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, presence: true, length: { minimum: 6 }

  validates_uniqueness_of :movie_id, scope: [:list_id]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :delete_all
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmarks_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmarks_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :destroy]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(lists_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # def edit
  # end

  # def update
  #   list = List.new(lists_params)
  #   list.save
  #   redirect_to list_path(list)
  # end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def lists_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for([@list, @bookmark]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :comment %>
    <%= f.association :movie, label: "Dogs" %>
    <%# f.input :entity_name, input_html: { name: 'entity[name]' }  %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/bookmarks/new.html.erb
<%= render "form", bookmark: @bookmark, list: @list%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
      <%= link_to lists_path, class: "navbar-brand" do %>
        <%= image_tag "https://icons.iconarchive.com/icons/google/noto-emoji-animals-nature/256/22214-dog-face-icon.png" %>
      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <%# if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "Home", "#", class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Messages", "#", class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <%= image_tag "https://media-exp1.licdn.com/dms/image/C5603AQEG9Catx_FA7w/profile-displayphoto-shrink_100_100/0/1517490506092?e=1674086400&v=beta&t=oSQv2twB4zvMDxWYGf0UK8ssiRv6JzqDB6ZJ-jQMr_A", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Action", "#", class: "dropdown-item" %>
                <%= link_to "Another action", "#", class: "dropdown-item" %>
                <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
              </div>
            </li>
          <%# else %>
            <!--li class="nav-item"-->
              <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
            <!--/li-->
          <%# end %>
        </ul>
      </div>
    </div>
  </div>
  </div>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/lists/index.html.erb
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.wagwalkingweb.com/media/daily_wag/sense_guides/can-dogs-see-in-a-dark-room/hero/can-dogs-see-in-a-dark-room_3rQvHxF.jpg);">
  <div class="container">
    <h1>Doggo Lists</h1>
    <p>Change your life by having a fuck ton of dogs.</p>
  </div>
</div>
<div class="container" data-controller="pages">
    <div class="d-flex justify-content-end">
      <%= link_to "Create a new list", new_list_path , class:'btn btn-success my-3' %>
    </div>
    <div class="list-container" >
      <% @lists.each do |list| %>
        <% if list.photo.attached? %>
          <% url = cl_image_path list.photo.key %>
        <% else %>
          <% url = "https://images.wagwalkingweb.com/media/daily_wag/sense_guides/can-dogs-see-in-a-dark-room/hero/can-dogs-see-in-a-dark-room_3rQvHxF.jpg" %>
        <% end %>
        <div class="card-trip">
          <img src=<%= url  %> />
          <div class="card-trip-infos">
            <div>
              <h2><%= link_to "#{list.name}", list_path(list) %></h2>
            </div>
            <h2 class="card-trip-pricing"><%= link_to "Delete", list_path(list), data: { turbo_method: :delete, turbo_confirm: "Delete #{list.name}?" } %></h2>
          </div>
        </div>
      <% end %>
    </div>
  </ul>
</div>

app/views/lists/new.html.erb
<%= render "form", list: @list%>

app/views/lists/show.html.erb
<% if @list.photo.attached? %>
  <% url = cl_image_path @list.photo.key, width: 100, heigth: 200%>
<% else %>
  <% url = "https://images.wagwalkingweb.com/media/daily_wag/sense_guides/can-dogs-see-in-a-dark-room/hero/can-dogs-see-in-a-dark-room_3rQvHxF.jpg" %>
<% end %>
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= url  %>)">
 <h1><%= @list.name %></h1>
</div>
<ul>
<div class="smallcont d-flex justify-content-between align-items-center px-4">
  <h2>Dogs</h2>
  <%= link_to "Add a dog",  new_list_bookmark_path(@list), class:'btn btn-success my-3' %>
</div>
<div class="list-container" >
      <% @list.bookmarks.each do |bookmark| %>
        <div class="card-trip">
          <div class="card-trip-infos">
            <div>
              <h2><%= bookmark.movie.title %> - <%= bookmark.movie.rating %><br>
                  <%= bookmark.movie.overview %> <br>
                  <br>
                  <i>"<%= bookmark.comment %>"!</i><br></h2>
            </div>
            <h2 class="card-trip-pricing"><%= link_to "Delete dog", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Delete?" }  %></h2>
          </div>
        </div>
      <% end %>
    </div>
</ul>